#######################
# Theme Customization #
#######################

title: Vishal Keshav                             # used in <title> tag & site header
author: Vishal Keshav                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  My personal page
slogan:                            # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://bulletcross.github.io              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/bulletcross # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/bulletcross
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: bulletcross       # you know, to protect you from bots. (handle and domain
    domain: gmail.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: DeepSea Plus Plus
    teaser: A C++ base tiny deep learning library, uses blaze for blazingly fast mathematics operations.
    url: https://github.com/bulletcross/TF_vs_Deep
    role: Creator
    category: Backend library
  - title: Xcelerator
    teaser: A python based framework for learning the modelling of model modelling procedure.
    url: https://github.com/bulletcross/xcelerator
    role: Creator
    category: Framework
  - title: UVA solutions
    teaser: Solutions to some of the mind-boggling competitive programming problems.
    url: https://github.com/bulletcross/UVa
    role: Solver
    category: Algorithm

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
